# Generated by Django 5.2.4 on 2025-07-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
